kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: artifactory-poc
  name:
    artifactory-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artifactory-poc
  template:
    metadata:
      labels:
        app: artifactory-poc
    spec:
      containers:
        - name: artifactory-poc
          image: IMAGE_REPO:VERSION
          ports:
          - containerPort: 80
          env:
          - name: TITLE
            value: "Artifactory POC"
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-poc  
  namespace: artifactory-poc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: artifactory-poc
