name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_NAME: acrlbpllcaks
  APP_NAME: artifactorypoc

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code 
      uses: actions/checkout@main

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${ env.REGISTRY_NAME }.azurecr.io
        username: ${ secrets.AZ_SP_CLIENT_ID }
        password: ${ secrets.AZ_SP_CLIENT_SECRET }

    - name: Build the Docker image
      run: docker build . -t ${ env.REGISTRY_NAME }.azurecr.io/${ env.APP_NAME }:${ github.run_number }

    - name: Push Image to Docker
      run: docker push ${ env.REGISTRY_NAME }.azurecr.io/${ env.APP_NAME }:${ github.run_number }
